### PR TITLE
Config timeout

### PR DESCRIPTION
**Pull request by Miq1**
Some MODBUS slaves are really slow answering. For those it is handy to be able to config the timeout value at runtime.

### CODE REVIEW

**Comment by bertmelis** [comment]
good addition.

However: I didn't include the check for negative pin numbers because this is already done in the Arduino functions (pinMode and digitalWrite). Don't know what is better: check here and avoid the function call or check twice.

**Comment by Miq1** [comment]
I thought that it might be clearer with the explicit ``if`` around the ``digitalWrite()`` calls, since the behaviour on negative pin numbers seems not to be documented officially. So any port of the Arduino environment to another platform could break it.
Performancewise it should not matter at all, as the call will have to load the pin number and check it against negative values anyway, so the compiler will most probably hold the comparison result in a register.

**Comment by bertmelis** [comment]
OK, I never looked to other platforms besides esp32/8266. And avoiding a function call is better then the redundant `if`.

**Comment by bertmelis** [comment]
Why did you make the timeout `static`?

**Comment by Miq1** [comment]
> 
> 
> Why did you make the timeout `static`?

Since I wanted to have just one class-wide value. If you are to deal with several esp32ModbusRTU instances at the same time, you may be better off with an object-based value, right.

Should I change it in another pull request?

Oh, by the way: I so far had created a separate branch for every change - should I stay with that or would you prefer larger chunks of changes for different topics?

**Comment by bertmelis** [comment]
I find it better to have it as a regular class member variable.

> Oh, by the way: I so far had created a separate branch for every change - should I stay with that or would you prefer larger chunks of changes for different topics?
Separate branches for separate PRs. I'd like to smash merge

**Comment by Miq1** [comment]
Okay, did so already (both: class member variable as another (well, 3 in fact) commit and separate branches ;))

**Pull request merged**
